version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ror-app .
      - docker tag ror-app:latest 229791758070.dkr.ecr.ap-south-1.amazonaws.com/ror-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 229791758070.dkr.ecr.ap-south-1.amazonaws.com/ror-app:latest
artifacts:
  files: imagedefinitions.json
