version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)  # Log in to your ECR registry
	  - REPOSITORY_URI=229791758070.dkr.ecr.ap-south-1.amazonaws.com/ror-app

  build:
    commands:
      - echo Building the Docker containers using docker-compose...
      - docker-compose -t $REPOSITORY_URI:latest -f docker-compose.yml build
      - docker-compose -t $REPOSITORY_URI:latest -f docker-compose.yml up -d

post_build:
  commands:
    - echo Pushing Docker images to ECR...
    - docker-compose -t $REPOSITORY_URI:latest -f docker-compose.yml push
    - echo Application deployment complete.
